### ISSUE TITLE
Edit: New Data Grabber with game name, acts like hack

### ISSUE THREAD

**Issue by Joshernoob** [RyanGreenup/cadmus#21]
![Screenshot 2024-02-07 005324](https://github.com/RyanGreenup/cadmus/assets/64944433/2d8ed9ca-dd41-4c07-ac1a-29e5679b1dd3)

Edit : seems that this is a "new" data grabber company are using and a lot of apps will be getting it so Name will be changed but it may be stolen

**Comment by RyanGreenup** [comment]
I don’t know anything about this.

I have no affiliation with that domain or any similar domain. 

I think you might have the wrong guy here,  this repo is just a shell script I used to take notes.
