### ISSUE TITLE
Add choice between silver searcher and recoll

### ISSUE THREAD

**Issue by danimateo** [RyanGreenup/cadmus#3]
I haven't used recoll before now, but from what I can see it isn't so great for fuzzy searching. What do you think about having a choice between this and Ag? Also, from what I can see, everything here is more like 'my way or the highway', what do you think about adding more configuration options?

**Comment by RyanGreenup** [comment]
> I haven't used recoll before now, but from what I can see it isn't so great for fuzzy searching. 

Recoll certainly wants the words to be 100% correct, I agree. Its GUI interface gives word suggestions but that's no good in the terminal.

It's great when you know that your note contains the words `iris`, `kmeans` and `ggplot` but not great when you need to fuzzy search.

> What do you think about having a choice between this and Ag? 

You might not be aware, because i haven't actually documented anything properly (I really should though), currently, you can press <kbd>Ctrl</kbd>+<kbd>q</kbd> to toggle interactive mode:

* `cadmus find`
    * ***Normal Mode***
        * will filter by file name
    * ***Interactive Mode***
        * will run `ripgrep` over the files and highlight any matches in the preview
*  `cadmus search`
    * ***Normal Mode***
        * will filter by file name
    * ***Interactive Mode***
        * will run *recoll* over the files

So you can fuzzy search with ripgrep not a problem.

If you think `Ag` will add something though yeah lets do it, I was just more familiar with `rg` so that's what I steared towards.

> Also, from what I can see, everything here is more like 'my way or the highway'

Yeah that's just a symptom of the fact that I wrote this more or less in 4/5 days to pull together my workflow (I feel sane now!).

Let's fix that, what kind of configuration options should we try and implement?

**Comment by danimateo** [comment]
> You might not be aware, because i haven't actually documented anything properly (I really should though), currently, you can press <kbd>Ctrl</kbd>+<kbd>q</kbd> to toggle interactive mode:

Yeah, wasn't aware. We should add this to the documentation.

> If you think `Ag` will add something though yeah lets do it, I was just more familiar with `rg` so that's what I steared towards.

I don't think there would be any noticeable difference, I mean Ag is a bit faster but it's not worth the switch for this case, as we re not expecting a huge number of files.

> Yeah that's just a symptom of the fact that I wrote this more or less in 4/5 days to pull together my workflow (I feel sane now!).

You did a great job for this time frame!

> Let's fix that, what kind of configuration options should we try and implement?

I'm not home atm, but I will check the script more thoroughly and maybe we can make something like an interactive config on the first install.

**Comment by RyanGreenup** [comment]
> Yeah, wasn't aware. We should add this to the documentation.

Yeah documentation is on the to do list for sure, what do you reckon, *GitHub*-Wiki, *MkDocs* or *DokuWiki*?

Here's a gif illustrating the behaviour:

![RipGrep Example](https://user-images.githubusercontent.com/47832594/87925534-c3c32100-cac3-11ea-902a-9cb9475e265a.gif)

> You did a great job for this time frame!

Thanks! You know what they say, necessity breeds innovation right :)

> it's not worth the switch for this case,

Yeah I agree, I think it'd be easier to just use `rg` throughout, pulling one out for the other will be a headache lol.

> make something like an interactive config on the first install.

So I actually just recently tried to implement that, [see this commit](https://github.com/RyanGreenup/cadmus/commit/343c3809c60c36f2cbef1e2993d951db203a5f4b) as well as a script to automate the clone and install, backup your install and try to install directly from the new instructions on the README and tell me how you go, (Although as per #2 we should implement an AUR package)

TBH the interactive script to generate the config isn't something I'm happy with, I couldn't figure out an elegant way to make [Skim](https://github.com/lotabout/skim) work well and for some reason that I haven't yet figured out, it is necessary to press enter twice after putting in the details, I'm definitely open to improvement on this front.

Could you make a new issue (or PR) for any improvements/changes we should implement in the interactive config?

Any other configuration options, that you'd like to see, just post an issue and we can start implementing them.
