### ISSUE TITLE
Implement Hascard for flashcards.

### ISSUE THREAD

**Issue by RyanGreenup** [RyanGreenup/cadmus#8]
[HasCard](https://github.com/Yvee1/hascard) will let us turn markdown files into flashcards, we should implement that because it would work well for recollection training. 

Perhaps card files could have a special tag `isHasCard ` and then Cadmus could use skim to pass a file to HasCard?

**Comment by danimateo** [comment]
I don't know if this is a good idea, it doesn't seem to integrate well with the rest of the tools. It needs a lot of special attention i.e., maybe it is better off as a standalone.

**Comment by RyanGreenup** [comment]
Yeah I agree, I saw I it and the more I think about it the more I think its a bad idea. I think I'll close this issue, thanks.
